name: Docs checker

on:
  pull_request:
    inputs:
      compiler:
        required: true
        type: string
      cxxcompiler:
        required: true
        type: string
      libraries:
        required: true
        type: string
      extra-cmake-parameters:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  commit-checker:
    name: New doxygen warnings checker
    runs-on: ubuntu-24.04
    env:
      CC: ${{ inputs.compiler }}
      CXX: ${{ inputs.cxxcompiler }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 4

    - name: Get pull-request commits
      uses: OpenTTD/actions/checkout-pull-request@v6

    - name: Setup vcpkg
      id: vcpkg
      uses: OpenTTD/actions/setup-vcpkg@v6

    - name: Install dependencies
      run: |
        echo "::group::Update apt"
        sudo apt-get update
        echo "::endgroup::"

        echo "::group::Install dependencies"
        sudo apt-get install -y --no-install-recommends \
          liballegro4-dev \
          libcurl4-openssl-dev \
          libfontconfig-dev \
          libharfbuzz-dev \
          libicu-dev \
          liblzma-dev \
          liblzo2-dev \
          libogg-dev \
          libopus-dev \
          libopusfile-dev \
          ${{ inputs.libraries }} \
          zlib1g-dev \
          doxygen \
          # EOF

        echo "::group::Install vcpkg dependencies"

        # Disable vcpkg integration, as we mostly use system libraries.
        mv vcpkg.json vcpkg-disabled.json

        # We only use breakpad from vcpkg, as its CMake files
        # are a bit special. So the Ubuntu's variant doesn't work.
        ${{ steps.vcpkg.outputs.vcpkg }} install breakpad

        echo "::endgroup::"
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install GCC problem matcher
      uses: ammaraskar/gcc-problem-matcher@master

    - name: Build docs for PR
      run: |
        mkdir build
        echo "WARN_LOGFILE = $(pwd)/doxygen_warnings.PR" >> Doxyfile.in
        echo "WARN_LOGFILE = $(pwd)/doxygen_AI_warnings.PR" >> src/script/api/Doxyfile_AI.in
        echo "WARN_LOGFILE = $(pwd)/doxygen_GS_warnings.PR" >> src/script/api/Doxyfile_GS.in
        echo "WARN_FORMAT = \$file: \$text" >> Doxyfile.in
        echo "WARN_FORMAT = \$file: \$text" >> src/script/api/Doxyfile_AI.in
        echo "WARN_FORMAT = \$file: \$text" >> src/script/api/Doxyfile_GS.in
        cd build
        cmake ..
        make docs -j 64
        cd ..
        rm -r build
        git restore Doxyfile.in src/script/api/Doxyfile_AI.in src/script/api/Doxyfile_GS.in

    - name: Build docs for base branch
      run: |
        git checkout HEAD^
        mkdir build
        echo "WARN_LOGFILE = $(pwd)/doxygen_warnings.base" >> Doxyfile.in
        echo "WARN_LOGFILE = $(pwd)/doxygen_AI_warnings.base" >> src/script/api/Doxyfile_AI.in
        echo "WARN_LOGFILE = $(pwd)/doxygen_GS_warnings.base" >> src/script/api/Doxyfile_GS.in
        echo "WARN_FORMAT = \$file: \$text" >> Doxyfile.in
        echo "WARN_FORMAT = \$file: \$text" >> src/script/api/Doxyfile_AI.in
        echo "WARN_FORMAT = \$file: \$text" >> src/script/api/Doxyfile_GS.in
        cd build
        cmake ..
        make docs -j 64
        cd ..
        rm -r build

    - name: Compare doxygen warnings and errors
      run: |
        sort doxygen_warnings.base > base.sorted
        sort doxygen_AI_warnings.base > base_AI.sorted
        sort doxygen_GS_warnings.base > base_GS.sorted
        sort doxygen_warnings.PR > PR.sorted
        sort doxygen_AI_warnings.PR > PR_AI.sorted
        sort doxygen_GS_warnings.PR > PR_GS.sorted
        comm -13 base.sorted PR.sorted > comm.output
        comm -13 base_AI.sorted PR_AI.sorted >> comm.output
        comm -13 base_GS.sorted PR_GS.sorted >> comm.output
        if [ -s comm.output ]; then cat comm.output; exit 1; fi
